<a href="https://www.kaggle.com/code/eishkaran/handwritten-text-recognition?scriptVersionId=119029142" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Handwritting Text Recoginition 

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/handwriting-data-set/train.csv
/kaggle/input/mnist-data/train.csv
/kaggle/input/mnist-data/test.csv


# Importhing the necessary Libraries 

In [2]:
import numpy as np  
import pandas as pd   #{for reading the csv files}
import matplotlib.pyplot as plt #{Using for plotting the graphs}
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score #{Machine learning algorithms imported}

# Adding the data

In [3]:
# Load the train.csv and test.csv files into pandas dataframes
train_df = pd.read_csv("/kaggle/input/handwriting-data-set/train.csv")
test_df = pd.read_csv("/kaggle/input/mnist-data/test.csv")
train_df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [4]:
# Split the train data into features (X) and labels (y)
X = train_df.drop("label", axis=1)
y = train_df["label"]

In [5]:
# Split the train data into train and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
# Create the K-Nearest Neighbors classifier model
knn = KNeighborsClassifier(n_neighbors=5)

# Training the Data On the basis of train data set

In [7]:
# Train the model on the training data
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [8]:
# Make predictions on the validation data
y_pred = knn.predict(X_val)

In [9]:
cm = confusion_matrix(y_val, y_pred)
accuracy = accuracy_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred, average="macro")

In [10]:
print("Confusion Matrix:")
print(cm)
print("Accuracy:", accuracy)
print("F1 Score:", f1)

Confusion Matrix:
[[806   0   2   0   0   2   3   0   0   0]
 [  0 956   2   1   0   0   0   1   1   0]
 [  9   6 829   3   0   0   1   9   3   0]
 [  1   1   4 836   0   6   0   6   4   5]
 [  1   7   0   0 795   0   4   1   0  19]
 [  2   1   1   8   0 734   7   0   1   2]
 [  0   1   0   0   1   2 837   0   0   0]
 [  0   9   4   1   4   0   0 874   0   7]
 [  3   8   0  16   4  20   8   3 699   7]
 [  5   2   1   5   9   3   2  19   0 766]]
Accuracy: 0.9680952380952381
F1 Score: 0.9675864822583169


In [11]:
# Make predictions on the test data
y_test_pred = knn.predict(test_df)
# Save the predictions to a CSV file
np.savetxt("y_test_pred.csv", y_test_pred, delimiter=",")